# Generated by Django 2.2.6 on 2019-11-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='game',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='players', through='game.PlayerGameInfo', to='game.Game'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='Игрок создатель'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player', verbose_name='Игрок'),
        ),
    ]
