# Generated by Django 2.2.6 on 2019-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191103_2250'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playergameinfo',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='player_game'),
        ),
    ]
