# Generated by Django 2.2.6 on 2019-11-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191103_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameinfo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player', verbose_name='Игрок'),
        ),
    ]
